### ISSUE TITLE
Update to yii 2.0.8

### ISSUE THREAD

**Issue by notgosu** [dmstr/yii2-migrate-command#17]
Hi there!

There are some nice improvements at 2.0.8 release related to migration controller, such as short keys.

Can you, please, update your package according to that functionality?

**Comment by schmunk42** [comment]
There's along standing issue to bring this feature to the core https://github.com/yiisoft/yii2/issues/384 - Happy 3rd birthday, issue 🍰 🎆 🎊 😃 

I think we won't find time soon to implement your request, but PRs are always welcome.

**Comment by schmunk42** [comment]
Closing, since this extension is no longer actively developed.
