### ISSUE TITLE
Migrate fails since latest update of yii2 ?

### ISSUE THREAD

**Issue by philippfrenzel** [dmstr/yii2-migrate-command#19]
```
Apply the above migrations? (yes|no) [no]:yes
*** applying m150127_040544_add_attachments
PHP Fatal error:  Class 'm150127_040544_add_attachments' not found in /app/vendor/dmstr/yii2-migrate-command/MigrateController.php on line 622
PHP Fatal Error 'yii\base\ErrorException' with message 'Class 'm150127_040544_add_attachments' not found'

in /app/vendor/dmstr/yii2-migrate-command/MigrateController.php:622

Stack trace:
#0 /app/vendor/dmstr/yii2-migrate-command/MigrateController.php(204): dmstr\console\controllers\MigrateController->migrateUp()
#1 /app/vendor/yiisoft/yii2/base/InlineAction.php(55): dmstr\console\controllers\MigrateController->actionUp()
#2 /app/vendor/yiisoft/yii2/base/InlineAction.php(55): ::call_user_func_array:{/app/vendor/yiisoft/yii2/base/InlineAction.php:55}()
#3 /app/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams()
#4 /app/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction()
#5 /app/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction()
#6 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#7 /app/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#8 /app/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest()
#9 /app/yii(27): yii\base\Application->run()
#10 {main}
```

[edit] formatting

**Comment by schmunk42** [comment]
There were some updates in Yii, but could you double check if you really have that class with the correct class-, file- and alias-name.

**Comment by philippfrenzel** [comment]
Hi, 

I tried out a couple of scenarios, one problem is, that the pages module doesn’t take care of table _prefix

{{%tablename}} instead of tablename ;)

And then for some reason I don’t understand the migrate command from the module:

https://github.com/Nemmo/yii2-attachments <https://github.com/Nemmo/yii2-attachments>

fails… I don’t understand it, as it used to work since last week …

Thanks for support!

**Comment by schmunk42** [comment]
Looks like it's because of the new alias support of migrations.

Our migrate command can not find it because this migration is not in the global namespace.
Don't have a quick solution for that at hand.

**Comment by philippfrenzel** [comment]
Thanks for trying to get feedback from the yii2 core team - looks like they friendly say you have to adopt the module ... :)

**Comment by schmunk42** [comment]
You might try running two separate migration steps as a quick workaround. 

One with this command and the original Yii command for namespaced migrations.

**Comment by philippfrenzel** [comment]
'yiimigrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationNamespaces' => [
                'nemmo\attachments\migrations',
            ],
        ],

**Comment by schmunk42** [comment]
Let's keep that open until it's completely resolved ;)

**Comment by schmunk42** [comment]
https://github.com/dmstr/yii2-migrate-command/commit/81fecdf73aa6a6a2be95f2cea7fa707199da82c9

You should get Yii 2.0.9 - if running the latest version if this extension now.
Depending on the outcome of the discussion in the Yii repo, we may update or deprecate this extension.

I think this one can be closed.
