### ISSUE TITLE
Some events support

### ISSUE THREAD

**Issue by JiLiZART** [dmstr/yii2-migrate-command#4]
Would be great to support some events like `before` and `after` all migrations execute.

Use case:
When all `tables` ready i can fill up rbac rules, or add some module specific data from another module

**Comment by schmunk42** [comment]
Can't you just simply wrap that into a script, like

```
before_migration.sh
./yii migrate
after_migrations.sh
```

What would be the advantage to the events? What should be send in the `$event` params?

**Comment by schmunk42** [comment]
Closing, since this extension is no longer actively developed.
