### ISSUE TITLE
SQL error -  Unknown column 'alias' in 'field list'

### ISSUE THREAD

**Issue by nagyt234** [dmstr/yii2-migrate-command#7]
I'm sure, that the problem is connected to the note:

```
"Note! If using dmstr/yii2-migrate-command in an existing project, you may have to remove your migration table, due to a schema change."
```

However we can not simply remove migration table, than all of the migration will re-run, causing a lot of errors. We should rather be instructed, how to migrate the migration table.

**Comment by omnilight** [comment]
You always can use command `yii migrate/mark mDDMMYY_HHMMSS` to add your migrations into the migration table after this extension is installed into the current project.

Hovever, I think that it should be mentioned in the README

**Comment by TheHett** [comment]
Where it say in REAME? 
it is not comfortable

**Comment by schmunk42** [comment]
Closing, since this extension is no longer actively developed.
